name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    
# on: push    # Default will running for every branch.1
    
jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         cache: true
         architecture: x64
     #- run: flutter config --enable-macos-desktop
     #- run: flutter build macos
     - run: flutter test
